Iwae
Intelligent-Systems-Phystech/DeepGenerativeModels pull request #2
Opened 2019-10-03 20:07 UTC by andriygav

Files added to the new repository and fixed comments

2019-10-04 09:00 UTC, r-isachenko requested changes

2019-10-04 09:00 UTC, r-isachenko commented on examples/utils.py
> +    Input: batch_of_x,   FloatTensor - the matrix of shape n x D.
ну давай заменим вездде эти n и D
пожаааааалуйста

2019-10-04 09:00 UTC, r-isachenko commented on examples/utils.py
> +    Input: optimizer,    Optimimazer - optimizer from torch.optim.
Optimimazer

2019-10-04 09:00 UTC, r-isachenko commented on examples/utils.py
> +    images_size=(
странная конструкция, это тебе autopep так сделал?
давай нормально напишем

2019-10-04 09:00 UTC, r-isachenko commented on src/DeepGenerativeModels/AutoEncoders.py
> +        Input: d,           int     - the dimension of latent space.
latent_dim видимо

2019-10-04 09:00 UTC, r-isachenko commented on src/DeepGenerativeModels/AutoEncoders.py
> +    def sample_z(self, distr, num_samples=1):
настаиваю на distr -> mu, sigma :)

2019-10-04 09:00 UTC, r-isachenko commented on src/DeepGenerativeModels/AutoEncoders.py
> +        distr_z = self.p_z(1)
num_samples=1

2019-10-04 09:00 UTC, r-isachenko commented on src/DeepGenerativeModels/AutoEncoders.py
> +        expectetion = torch.mean(self.log_mean_exp(exponent), dim=0)
во-первых, expectetion -> expectation

а во-вторых, или я туплю или тут не то
тут же сумма логарифмов вышла, а нужен логарифм суммы, не?

2019-10-04 09:39 UTC, andriygav commented on src/DeepGenerativeModels/AutoEncoders.py
> +        expectetion = torch.mean(self.log_mean_exp(exponent), dim=0)
не, там верно, у тебя есть усреднение по сэмплам для Importance sampling (под логарифмом --- функция log_mean_exp это делает, отсюда и название функции), а еще отдельно усреднение по обещающейся подборке --- функция torch.mean делает. Последний torch.mean нужен чтобы в вектор из одного числа превратить скаляр --- torch.mean который в return (чисто техническое среднее)

2019-10-04 09:41 UTC, andriygav commented on src/DeepGenerativeModels/AutoEncoders.py
> +    def sample_z(self, distr, num_samples=1):
нет, это жутко не правильно разносить сущности:) более правильное distr, так это один объект и одна сущность

2019-10-04 09:41 UTC, andriygav commented on examples/utils.py
> +    Input: batch_of_x,   FloatTensor - the matrix of shape n x D.
Да я уже везде заменил, просто иногда их пропустил, так как их через стандартную замену не заменишь и надо глазками искать

2019-10-05 17:33 UTC, r-isachenko approved these changes

2019-10-05 17:33 UTC, r-isachenko commented on src/DeepGenerativeModels/AutoEncoders.py
> +    def sample_z(self, distr, num_samples=1):
я тебе уже отвечал на твои эти аргументы

2019-10-05 17:38 UTC, merged