Neural ODE is coming
Intelligent-Systems-Phystech/DeepGenerativeModels pull request #7
Opened 2019-10-09 22:29 UTC by FilippNikitin

We offered a suitable realization of the Adjoint Method with PyTorch. The module allows implementing continuous neural networks to any PyTorch modes quickly and efficiently.    

- PyTorch autograd ODE solver 
- Adjoint Autograd 
- Continuous classifier for MNIST
- ResNet classifier for MNIST
- Example with a simple dynamic system 

To be here:
- Final notebooks
- Continuous Flow example
- Documentation

2019-10-10 13:43 UTC, r-isachenko requested changes

2019-10-10 13:43 UTC, r-isachenko commented on src/DeepGenerativeModels/NeuralODE/adjoint_ode.py
> +    return euler_update(state, func(state), dt)
дублируются в ноутбуке

2019-10-10 13:43 UTC, r-isachenko commented on src/DeepGenerativeModels/NeuralODE/adjoint_ode.py
> +    return euler_update(state, func(state), dt)
в ноутбуке нельзя оставлять комментарии, поэтому здесь напишу
- пусть plot_trajectory принимает dict: {label: trajectory}
- вынести бы переменные типа число шагов, шаг обучения и тд хотя в отдельную ячейку, а то совсем хардкод
- не хватает комментариев, очень тяжело читать (всё на англ пиши)
- не хватает секции с выводом

2019-10-10 13:43 UTC, r-isachenko commented on src/DeepGenerativeModels/NeuralODE/adjoint_ode.py
> +class AdjointODE(nn.Module):
задокумментируй всё, пожалуйста, по максимуму, иначе я умру разбираться в этом всём

2019-10-11 09:19 UTC, newfteddy commented on src/DeepGenerativeModels/NeuralODE/adjoint_ode.py
> +    return euler_update(state, func(state), dt)
Все комменты учтены, внес правки в последнем коммите

2019-10-13 09:22 UTC, r-isachenko approved these changes

2019-10-13 09:23 UTC, merged